### ISSUE TITLE
Google Chart Tooltip formatting

### ISSUE THREAD

**Issue by doctorpot1** [doctorpot1/forZL#3]
Instead of 0.2hours format it to be minutes instead.

**Comment by doctorpot1** [comment]
Fixed in https://github.com/doctorpot1/attendance-demux/commit/17adf4c0e1c75b3b92629147c508787410e39d3e

**Comment by zhongliangong** [comment]
Fixed in 0ed19798666bf6f2b8b107cd8fa872bbbbc516bf
